In [4]:
# Importation de la librairie Pandas
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier 
import joblib
import pickle

### Example 1 : Random Forest

In [6]:
# Importation du fichier billet_production.csv

X = pd.read_csv("Data/billets_production.csv")

In [7]:
X

diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

In [9]:
# Créer une variable avec l'ordre exact des features lors de l'entraînement et prédiction

predictors = ["diagonal", "height_left", "height_right", "length", "margin_low", "margin_up"]

In [10]:
# Exclure les features qui n'étaient pas présentes dans le DF lors du training

X = X.drop(["id"], axis=1)

In [11]:
with open('random_forest_model.pkl', 'rb') as f:
 loaded_models = pickle.load(f)

# Faire des prédictions en utilisant le modèle chargé
y_pred = loaded_models.predict(X[predictors])

In [12]:
y_pred

array([0, 0, 0, 1, 1], dtype=int64)

### Example 2 : Random Forest

In [14]:

df= pd.read_csv("Data/billets_test.csv")

In [15]:
df

diagonal  height_left  height_right  margin_low  margin_up  length   id
0    172.09       103.95        103.73        4.39       3.09  113.19  B_1
1    171.52       104.17        104.03        5.27       3.16  111.82  B_2
2    171.78       103.80        103.75        3.81       3.24  113.39  B_3
3    172.02       104.08        103.99        5.57       3.30  111.10  B_4
4    171.79       104.34        104.37        5.00       3.07  111.87  B_5

In [16]:
predictors = ["diagonal", "height_left", "height_right", "length", "margin_low", "margin_up"]

In [17]:
df = df.drop(["id"], axis=1)

In [18]:
df

diagonal  height_left  height_right  margin_low  margin_up  length
0    172.09       103.95        103.73        4.39       3.09  113.19
1    171.52       104.17        104.03        5.27       3.16  111.82
2    171.78       103.80        103.75        3.81       3.24  113.39
3    172.02       104.08        103.99        5.57       3.30  111.10
4    171.79       104.34        104.37        5.00       3.07  111.87

In [19]:
with open('random_forest_model.pkl', 'rb') as f:
 new_rf = pickle.load(f)

# Faire des prédictions en utilisant le modèle chargé
y_pred = new_rf.predict(df[predictors])

In [20]:
y_pred 

array([1, 0, 1, 0, 0], dtype=int64)

### Example 3 : Gradient Boosting

In [36]:
with open('gbr2_model.pkl', 'rb') as f:
 new_gbr = pickle.load(f)

# Faire des prédictions en utilisant le modèle chargé
y_pred = new_gbr.predict(df[predictors])

In [38]:
y_pred

array([1, 0, 1, 0, 0], dtype=int64)

### Example 4 : XGBoost

In [23]:
with open('opt_model.pkl', 'rb') as f:
 new_opt = pickle.load(f)

# Faire des prédictions en utilisant le modèle chargé
y_pred = new_opt.predict(df[predictors])

In [25]:
y_pred

array([1, 0, 1, 0, 0])